import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-red-500 sm:text-green-500 md:text-pink-500 lg:text-purple-500 xl:text-yellow-500 2xl:text-blue-500'>
        HEY
      </h1>
    </div>
  );
}
